### ISSUE TITLE
Camera calibration

### ISSUE THREAD

**Issue by SujithChristopher** [herohuyongtao/deeptag-pytorch#4]
How to calibrate the camera using this library, If I use my CameraMatrix and DistortionCoeff from OpenCV library, the markers are not detecting.

**Comment by sskzzm** [comment]
Please copy the values of  CameraMatrix/DistortionCoeff to our provided configuration file (in .json format).

**Comment by SujithChristopher** [comment]
Thank you for your reply @sskzzm , Yes, i tried that too, as mentioned previously in my question. I calibrated using aruco modules from OpenCV contrib library. But the situation remains the same, unable to detect the markers.

**Comment by sskzzm** [comment]
You may try to undistort the image with cv::undistort (https://docs.opencv.org/3.4/da/d54/group__imgproc__transform.html) and check whether the resulted image looks normal. If the undistorted image is fine, use the undistorted one instead of the originally captured one as input, and then in .json file, only configure CameraMatrix while setting DistortionCoeff  with all zero values.
